name: Build

env:
  TZ: Asia/Jakarta
on:
  workflow_dispatch:
jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
            wget https://raw.githubusercontent.com/malkist01/Android-A15/main/build-kernel.sh
            bash build-kernel.sh          
