name: Build Kernel
on:
  workflow_dispatch:
env:
  TZ: Asia/Jakarta
jobs:
  teletubiesbuild:
    runs-on: ubuntu-22.04
  steps:
    - name: Creating Env!
      uses: actions/checkout@v2
      
    - name: Setting up Env!
       run: |
           chmod +x build-kernel.sh
           ./build-kernel.sh
      shell: bash
