name: Build Kernel
on:
  workflow_dispatch:
env:
  TZ: Asia/Jakarta
jobs:
  kernel-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Initializing environment
        run: |    
            bash build-kernel.sh
