name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'device codename (e.g mido)'
          default: 'mido'
          required: true
      repo:
          description: 'Kernel source link (dont include . git at the end)'
        default: 'https://github.com/malkist01/Teletubies-toni.git'
          required: true
      branch:
          description: 'Kernel source branch'
          default: 'Toni'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7596553794:AAGoeg4VypmUfBqfUML5VWt5mjivN5-3ah8'
          required: true
      chat_id:
          description: 'Telegram chat id'
          defult: '-1002287610863'
          required: true
      kernelsu:
        description: 'KernelSU | false if source not support'
        default: 'curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next'
        required: true


env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  GKI: ${{ github.event.inputs.gki }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "malkist01"
          git config --global user.email "aripujiyanto0812@gmail.com"
         git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh
          
      - name: Compiling
        run: |
          if [ "${DEVICE}" = "mido" ]; then
            wget https://raw.githubusercontent.com/malkist01/kernel_build_action/main/scripts/mido_build_script.sh
            bash mido_build_script.sh
          else
            echo "Device not supported yet"
          fi

