name: teletubies-main
on:
   workflow_dispatch:

env:
  TZ: Asia/Jakarta
  
jobs:
  teletubiesbuild:
       runs-on: ubuntu-22.04

       steps:
       - name: Creating env!
         uses: actions/checkout@v2

       - name: Setting up env!
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install git make bc bison -y ccache \
              openssl curl zip kmod cpio flex libelf-dev \
              libssl-dev libtfm-dev wget device-tree-compiler \
              ca-certificates python3 python2 binutils \
              binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
       - name: Building Kernel...
         run: |
             chmod +x build.sh && bash build.sh
             chmod +x patches.sh && bash patches.sh
             shell: bash
             env:
              CHATID: ${{ secrets.CHAT_ID }}
              API_BOT: ${{ secrets.BOT_API }}

